services:
  hi-bot:
    build: .
    container_name: hi-bot
    restart: unless-stopped

    env_file:
      - .env

    networks:
      - hi-bot-net

    volumes:
      - hibot_base_videos:/app/base_videos
      - hibot_fonts:/app/fonts

    ports:
      - "8080:8080"

networks:
  hi-bot-net:
    name: hi-bot-net
    driver: bridge

volumes:
  hibot_base_videos:
  hibot_fonts: